/* Generated by Cython 0.29.36 */

#ifndef __PYX_HAVE__sqliteplus__utils__sqliteplus_sync
#define __PYX_HAVE__sqliteplus__utils__sqliteplus_sync

#include "Python.h"

#ifndef __PYX_HAVE_API__sqliteplus__utils__sqliteplus_sync

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *SQLITEPLUS_PUBLIC_API;

#endif /* !__PYX_HAVE_API__sqliteplus__utils__sqliteplus_sync */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initsqliteplus_sync(void);
#else
PyMODINIT_FUNC PyInit_sqliteplus_sync(void);
#endif

#endif /* !__PYX_HAVE__sqliteplus__utils__sqliteplus_sync */
